package com.innovify.skillswap.learningpathengine.domain.model.aggregates;

import com.innovify.skillswap.learningpathengine.domain.model.entities.Question;
import com.innovify.skillswap.learningpathengine.infrastructure.persistence.jpa.converters.QuestionListConverter;
import com.innovify.skillswap.shared.domain.exceptions.DomainException;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * Specification of the assessment generated by AI to demonstrate the skill of one path node. It is consumed by
 * Assessment &amp; Peer Review. Older blueprints of a node are kept as history; the node points to the latest.
 *
 * <p>The questions are stored in the blueprint's JSON column, never as an entity of their own. The converter that
 * writes them is the one JPA annotation of this class that points outside the domain, because a list cannot be
 * matched by an auto-applied converter.
 */
@Entity
@Table(name = "assessment_blueprints")
public class AssessmentBlueprint {

    public static final int QUESTION_COUNT = 5;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @Column(name = "path_node_id", nullable = false)
    private int pathNodeId;

    @Column(name = "skill_tag", nullable = false, length = 100)
    private String skillTag;

    @Convert(converter = QuestionListConverter.class)
    @Column(name = "questions", nullable = false, columnDefinition = "jsonb")
    private List<Question> questions;

    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;

    /** Required by JPA. */
    protected AssessmentBlueprint() {
    }

    /**
     * @throws DomainException when the node or the skill are not valid, or the questions are not exactly
     *                         {@value #QUESTION_COUNT} different ones
     */
    public AssessmentBlueprint(int pathNodeId, String skillTag, Collection<Question> questions) {
        if (pathNodeId <= 0) {
            throw new DomainException("The blueprint must belong to a valid path node.");
        }
        if (skillTag == null || skillTag.isBlank()) {
            throw new DomainException("The skill tag cannot be empty.");
        }

        List<Question> list = questions == null ? List.of() : List.copyOf(questions);
        if (list.size() != QUESTION_COUNT) {
            throw new DomainException("An assessment needs exactly %d questions.".formatted(QUESTION_COUNT));
        }
        Set<String> texts = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
        list.forEach(question -> texts.add(question.getQuestionString()));
        if (texts.size() != list.size()) {
            throw new DomainException("The questions of an assessment must be different from each other.");
        }

        this.pathNodeId = pathNodeId;
        this.skillTag = skillTag.strip();
        this.questions = list;
        this.generatedAt = Instant.now();
    }

    public Integer getId() {
        return id;
    }

    public int getPathNodeId() {
        return pathNodeId;
    }

    public String getSkillTag() {
        return skillTag;
    }

    public List<Question> getQuestions() {
        return questions;
    }

    public Instant getGeneratedAt() {
        return generatedAt;
    }
}
