package com.innovify.skillswap.iam.domain.model;

public enum IamError {
    NONE,
    INVALID_CREDENTIALS,
    USER_BANNED,
    USERNAME_ALREADY_TAKEN,
    EMAIL_ALREADY_TAKEN,
    INVALID_INSTITUTIONAL_EMAIL,
    INVALID_USERNAME,
    WEAK_PASSWORD,
    USER_NOT_FOUND,
    NOT_PROFILE_OWNER,
    BIO_TOO_LONG,
    OPERATION_CANCELLED,
    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR
}
