-- Mirror of the tables created by the C# API's EF Core migration (AddAssessmentPeerReview). Hibernate only
-- validates them (ddl-auto=validate), so a mapping that drifts from the real schema fails the tests.
DROP TABLE IF EXISTS assessment_attempts;
DROP TABLE IF EXISTS verification_cases;
DROP TABLE IF EXISTS verifier_profiles;

CREATE TABLE assessment_attempts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blueprint_id integer NOT NULL,
    student_id integer NOT NULL,
    selected_answers jsonb NOT NULL,
    score character varying(10) NOT NULL,
    passed boolean NOT NULL,
    completed_at timestamp with time zone NOT NULL
);

CREATE TABLE verification_cases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id integer NOT NULL,
    student_id integer NOT NULL,
    verifier_user_id integer,
    path_node_id integer NOT NULL,
    skill_tag character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    decision character varying(20),
    rubric_notes character varying(2000),
    evidence_url character varying(500),
    opened_at timestamp with time zone NOT NULL,
    assigned_at timestamp with time zone,
    resolved_at timestamp with time zone,
    appeal_count integer NOT NULL DEFAULT 0,
    previous_verifier_user_id integer
);

CREATE TABLE verifier_profiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verifier_user_id integer NOT NULL,
    skill_tags jsonb NOT NULL,
    available boolean NOT NULL,
    verified boolean NOT NULL,
    rating double precision NOT NULL,
    review_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE INDEX "IX_assessment_attempts_student_id" ON assessment_attempts (student_id);
CREATE UNIQUE INDEX ux_assessment_attempts_blueprint ON assessment_attempts (blueprint_id);
CREATE INDEX "IX_verification_cases_skill_tag_status" ON verification_cases (skill_tag, status);
CREATE INDEX "IX_verification_cases_verifier_user_id" ON verification_cases (verifier_user_id);
CREATE UNIQUE INDEX ux_verification_cases_attempt ON verification_cases (attempt_id);
CREATE UNIQUE INDEX ux_verification_cases_one_open_per_student_node
    ON verification_cases (student_id, path_node_id) WHERE status <> 'Resolved';
CREATE UNIQUE INDEX ux_verifier_profiles_user ON verifier_profiles (verifier_user_id);
