-- Mirror of the "certificates" table created by the C# API's EF Core migration (AddCertificates). Hibernate only
-- validates it (ddl-auto=validate), so a mapping that drifts from the real schema fails the tests.
DROP TABLE IF EXISTS certificates;

CREATE TABLE certificates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL,
    holder_name character varying(255),
    institution_name character varying(255),
    course_name character varying(255),
    issue_date date,
    duration_hours integer,
    certificate_number character varying(255),
    verification_code character varying(255),
    verification_url character varying(2048),
    qr_payload character varying(4096),
    ocr_text text NOT NULL,
    file_hash character varying(64) NOT NULL,
    storage_reference character varying(512) NOT NULL,
    status character varying(20) NOT NULL,
    verification_method character varying(20) NOT NULL,
    risk_score integer,
    created_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone
);

CREATE UNIQUE INDEX "IX_certificates_owner_id_file_hash" ON certificates (owner_id, file_hash);
CREATE INDEX "IX_certificates_certificate_number" ON certificates (certificate_number);
CREATE INDEX "IX_certificates_verification_code" ON certificates (verification_code);
CREATE INDEX "IX_certificates_file_hash" ON certificates (file_hash);
