-- Mirror of the "users" table created by the C# API's EF Core migration (InitialCreate). Hibernate only
-- validates it (ddl-auto=validate), so a mapping that drifts from the real schema fails the tests.
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    is_verified boolean NOT NULL,
    bio character varying(1000) NOT NULL,
    device_token character varying(512)
);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);
CREATE UNIQUE INDEX "IX_users_username" ON users (username);
