-- Mirror of the tables created by the C# API's EF Core migration (AddLearningPathEngine). Hibernate only
-- validates them (ddl-auto=validate), so a mapping that drifts from the real schema fails the tests.
DROP TABLE IF EXISTS path_nodes;
DROP TABLE IF EXISTS learning_paths;
DROP TABLE IF EXISTS assessment_blueprints;

CREATE TABLE assessment_blueprints (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_node_id integer NOT NULL,
    skill_tag character varying(100) NOT NULL,
    questions jsonb NOT NULL,
    generated_at timestamp with time zone NOT NULL
);

CREATE TABLE learning_paths (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    career_goal jsonb NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE path_nodes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_tag character varying(100) NOT NULL,
    node_order integer NOT NULL,
    status character varying(20) NOT NULL,
    prerequisites character varying(1000) NOT NULL,
    linked_certificate_id integer,
    assessment_blueprint_id integer,
    learning_path_id integer NOT NULL,
    CONSTRAINT "FK_path_nodes_learning_paths_learning_path_id" FOREIGN KEY (learning_path_id)
        REFERENCES learning_paths (id) ON DELETE CASCADE
);

CREATE INDEX "IX_assessment_blueprints_path_node_id" ON assessment_blueprints (path_node_id);
CREATE UNIQUE INDEX ux_learning_paths_one_active_per_student ON learning_paths (student_id) WHERE status = 'Active';
CREATE UNIQUE INDEX "IX_path_nodes_learning_path_id_node_order" ON path_nodes (learning_path_id, node_order);
CREATE UNIQUE INDEX "IX_path_nodes_learning_path_id_skill_tag" ON path_nodes (learning_path_id, skill_tag);
