-- Mirror of the "wallets" and "credit_transactions" tables created by the C# API's EF Core migration
-- (AddRecognitionIncentives). The "xmin" concurrency token of the C# API is not mirrored: the Java API locks the
-- wallet row instead. Hibernate only validates the schema (ddl-auto=validate).
DROP TABLE IF EXISTS credit_transactions;
DROP TABLE IF EXISTS wallets;

CREATE TABLE wallets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_owner_id integer NOT NULL,
    balance integer NOT NULL,
    CONSTRAINT ck_wallets_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE credit_transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id integer NOT NULL,
    amount integer NOT NULL,
    type character varying(20) NOT NULL,
    description character varying(200) NOT NULL,
    related_case_id integer,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credit_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT "FK_credit_transactions_wallets_wallet_id" FOREIGN KEY (wallet_id)
        REFERENCES wallets (id) ON DELETE CASCADE
);

CREATE INDEX "IX_credit_transactions_wallet_id" ON credit_transactions (wallet_id);
CREATE UNIQUE INDEX ux_credit_transactions_wallet_case ON credit_transactions (wallet_id, related_case_id)
    WHERE related_case_id IS NOT NULL;
CREATE UNIQUE INDEX ux_wallets_owner ON wallets (wallet_owner_id);
