DROP TABLE IF EXISTS verifier_reliabilities;
DROP TABLE IF EXISTS student_employability_scores;

CREATE TABLE student_employability_scores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    verified_skills_count integer NOT NULL,
    score integer NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE verifier_reliabilities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verifier_user_id integer NOT NULL,
    resolved_cases_count integer NOT NULL,
    overturned_decisions_count integer NOT NULL,
    sanctions_count integer NOT NULL,
    score integer NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX ux_student_employability_scores_student ON student_employability_scores (student_id);
CREATE UNIQUE INDEX ux_verifier_reliabilities_user ON verifier_reliabilities (verifier_user_id);
