-- US13 and US14: a suspicious certificate is escalated to a Verificador senior through Moderation & Disputes.

-- Identity & Access: the full name the student registered, which the holder read from their certificates must
-- match. It is optional: the accounts created before it have none, and their certificates are not compared.
ALTER TABLE users
    ADD COLUMN full_name character varying(150);

-- Credential Verification: whether the holder read by the OCR differs from the registered name of the owner.
-- The certificates registered before the comparison existed were never compared, so they start as false.
ALTER TABLE certificates
    ADD COLUMN holder_name_mismatch boolean NOT NULL DEFAULT false;

-- Moderation & Disputes: a case that needs the final decision of a Verificador senior. Only the escalation of a
-- suspicious certificate (CertificateReview) is created today; the other origins of the report are reserved. The
-- case is assigned to a senior, or to another enabled verifier when there is no senior, and never to the owner of
-- the certificate (respondent).
CREATE TABLE disputes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    source_type character varying(40) NOT NULL,
    source_reference_id integer NOT NULL,
    raised_by_user_id integer,
    respondent_user_id integer,
    reason character varying(500) NOT NULL,
    status character varying(20) NOT NULL,
    outcome character varying(20),
    coordinator_notes character varying(2000),
    assigned_verifier_user_id integer,
    assigned_to_senior boolean NOT NULL DEFAULT false,
    assigned_at timestamp with time zone,
    raised_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT pk_disputes PRIMARY KEY (id),
    CONSTRAINT ck_disputes_source_type
        CHECK (source_type IN ('CertificateReview', 'VerifierDecisionAppeal', 'UserReport')),
    CONSTRAINT ck_disputes_status CHECK (status IN ('Pending', 'Resolved')),
    CONSTRAINT ck_disputes_outcome
        CHECK (outcome IS NULL OR outcome IN ('Upheld', 'Overturned', 'Dismissed', 'Sanctioned')),
    CONSTRAINT ck_disputes_not_reviewed_by_respondent
        CHECK (assigned_verifier_user_id IS NULL OR respondent_user_id IS NULL
            OR assigned_verifier_user_id <> respondent_user_id)
);

-- A certificate is escalated once, however many times the event that escalates it is delivered.
CREATE UNIQUE INDEX ux_disputes_certificate_review ON disputes (source_reference_id)
    WHERE source_type = 'CertificateReview';
-- The disputes assigned to a verifier, and the ones still waiting for one.
CREATE INDEX ix_disputes_assigned_verifier_user_id_status ON disputes (assigned_verifier_user_id, status);
CREATE INDEX ix_disputes_unassigned_pending ON disputes (raised_at)
    WHERE status = 'Pending' AND assigned_verifier_user_id IS NULL;
