-- Baseline: the schema the entities expect, as it already exists in the shared database. The tables were created
-- by the C# API's EF Core migrations (InitialCreate .. AddRecognitionIncentives) and the two appeal columns of
-- verification_cases were added afterwards by hand; the names of the keys, foreign keys and indexes are the ones
-- EF Core gave them. On that database this script never runs: Flyway records it as the baseline
-- (spring.flyway.baseline-on-migrate, baseline-version=1). On an empty database (tests, local) it creates
-- everything. Hibernate only validates the result (ddl-auto=validate).

-- IAM

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    is_verified boolean NOT NULL,
    bio character varying(1000) NOT NULL,
    device_token character varying(512),
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);
CREATE UNIQUE INDEX "IX_users_username" ON users (username);

-- Credential Verification

CREATE TABLE certificates (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    owner_id integer NOT NULL,
    holder_name character varying(255),
    institution_name character varying(255),
    course_name character varying(255),
    issue_date date,
    duration_hours integer,
    certificate_number character varying(255),
    verification_code character varying(255),
    verification_url character varying(2048),
    qr_payload character varying(4096),
    ocr_text text NOT NULL,
    file_hash character varying(64) NOT NULL,
    storage_reference character varying(512) NOT NULL,
    status character varying(20) NOT NULL,
    verification_method character varying(20) NOT NULL,
    risk_score integer,
    created_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone,
    CONSTRAINT "PK_certificates" PRIMARY KEY (id)
);

CREATE INDEX "IX_certificates_certificate_number" ON certificates (certificate_number);
CREATE INDEX "IX_certificates_file_hash" ON certificates (file_hash);
CREATE UNIQUE INDEX "IX_certificates_owner_id_file_hash" ON certificates (owner_id, file_hash);
CREATE INDEX "IX_certificates_verification_code" ON certificates (verification_code);

-- Learning Path Engine

CREATE TABLE assessment_blueprints (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    path_node_id integer NOT NULL,
    skill_tag character varying(100) NOT NULL,
    questions jsonb NOT NULL,
    generated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_assessment_blueprints" PRIMARY KEY (id)
);

CREATE TABLE learning_paths (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    career_goal jsonb NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_learning_paths" PRIMARY KEY (id)
);

CREATE TABLE path_nodes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    skill_tag character varying(100) NOT NULL,
    node_order integer NOT NULL,
    status character varying(20) NOT NULL,
    prerequisites character varying(1000) NOT NULL,
    linked_certificate_id integer,
    assessment_blueprint_id integer,
    learning_path_id integer NOT NULL,
    CONSTRAINT "PK_path_nodes" PRIMARY KEY (id),
    CONSTRAINT "FK_path_nodes_learning_paths_learning_path_id" FOREIGN KEY (learning_path_id)
        REFERENCES learning_paths (id) ON DELETE CASCADE
);

CREATE INDEX "IX_assessment_blueprints_path_node_id" ON assessment_blueprints (path_node_id);
-- A student has at most one active path.
CREATE UNIQUE INDEX ux_learning_paths_one_active_per_student ON learning_paths (student_id) WHERE status = 'Active';
CREATE UNIQUE INDEX "IX_path_nodes_learning_path_id_node_order" ON path_nodes (learning_path_id, node_order);
CREATE UNIQUE INDEX "IX_path_nodes_learning_path_id_skill_tag" ON path_nodes (learning_path_id, skill_tag);

-- Assessment & Peer Review

CREATE TABLE assessment_attempts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    blueprint_id integer NOT NULL,
    student_id integer NOT NULL,
    selected_answers jsonb NOT NULL,
    score character varying(10) NOT NULL,
    passed boolean NOT NULL,
    completed_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_assessment_attempts" PRIMARY KEY (id)
);

CREATE TABLE verification_cases (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    attempt_id integer NOT NULL,
    student_id integer NOT NULL,
    verifier_user_id integer,
    path_node_id integer NOT NULL,
    skill_tag character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    decision character varying(20),
    rubric_notes character varying(2000),
    evidence_url character varying(500),
    opened_at timestamp with time zone NOT NULL,
    assigned_at timestamp with time zone,
    resolved_at timestamp with time zone,
    appeal_count integer NOT NULL DEFAULT 0,
    previous_verifier_user_id integer,
    CONSTRAINT "PK_verification_cases" PRIMARY KEY (id)
);

CREATE TABLE verifier_profiles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    verifier_user_id integer NOT NULL,
    skill_tags jsonb NOT NULL,
    available boolean NOT NULL,
    verified boolean NOT NULL,
    rating double precision NOT NULL,
    review_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_verifier_profiles" PRIMARY KEY (id)
);

CREATE INDEX "IX_assessment_attempts_student_id" ON assessment_attempts (student_id);
CREATE UNIQUE INDEX ux_assessment_attempts_blueprint ON assessment_attempts (blueprint_id);
CREATE INDEX "IX_verification_cases_skill_tag_status" ON verification_cases (skill_tag, status);
CREATE INDEX "IX_verification_cases_verifier_user_id" ON verification_cases (verifier_user_id);
CREATE UNIQUE INDEX ux_verification_cases_attempt ON verification_cases (attempt_id);
-- A student has at most one open case per node.
CREATE UNIQUE INDEX ux_verification_cases_one_open_per_student_node
    ON verification_cases (student_id, path_node_id) WHERE status <> 'Resolved';
CREATE UNIQUE INDEX ux_verifier_profiles_user ON verifier_profiles (verifier_user_id);

-- Reputation

CREATE TABLE student_employability_scores (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    verified_skills_count integer NOT NULL,
    score integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_student_employability_scores" PRIMARY KEY (id)
);

CREATE TABLE verifier_reliabilities (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    verifier_user_id integer NOT NULL,
    resolved_cases_count integer NOT NULL,
    overturned_decisions_count integer NOT NULL,
    sanctions_count integer NOT NULL,
    score integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_verifier_reliabilities" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_student_employability_scores_student ON student_employability_scores (student_id);
CREATE UNIQUE INDEX ux_verifier_reliabilities_user ON verifier_reliabilities (verifier_user_id);

-- Recognition & Incentives

CREATE TABLE wallets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    wallet_owner_id integer NOT NULL,
    balance integer NOT NULL,
    CONSTRAINT "PK_wallets" PRIMARY KEY (id),
    CONSTRAINT ck_wallets_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE credit_transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    wallet_id integer NOT NULL,
    amount integer NOT NULL,
    type character varying(20) NOT NULL,
    description character varying(200) NOT NULL,
    related_case_id integer,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_credit_transactions" PRIMARY KEY (id),
    CONSTRAINT ck_credit_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT "FK_credit_transactions_wallets_wallet_id" FOREIGN KEY (wallet_id)
        REFERENCES wallets (id) ON DELETE CASCADE
);

CREATE INDEX "IX_credit_transactions_wallet_id" ON credit_transactions (wallet_id);
-- A case pays a wallet only once.
CREATE UNIQUE INDEX ux_credit_transactions_wallet_case ON credit_transactions (wallet_id, related_case_id)
    WHERE related_case_id IS NOT NULL;
CREATE UNIQUE INDEX ux_wallets_owner ON wallets (wallet_owner_id);
