-- Subscription & Billing: the monthly subscription of a student, verified with Google Play Billing through
-- RevenueCat. A student without a subscription that has not expired is on the free plan, so the free plan has no
-- rows. The plan is stored flattened (name, store product, price and currency); nothing about the payment method
-- is stored: Google Play keeps it.

CREATE TABLE subscriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    student_id integer NOT NULL,
    plan_name character varying(50) NOT NULL,
    plan_product_id character varying(100) NOT NULL,
    plan_price numeric(10, 2) NOT NULL,
    plan_currency character varying(3) NOT NULL,
    status character varying(20) NOT NULL,
    store_transaction_id character varying(255),
    started_at timestamp with time zone NOT NULL,
    current_period_end timestamp with time zone NOT NULL,
    cancelled_at timestamp with time zone,
    expired_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    CONSTRAINT ck_subscriptions_status CHECK (status IN ('Active', 'Cancelled', 'Expired')),
    CONSTRAINT ck_subscriptions_plan_price_non_negative CHECK (plan_price >= 0)
);

-- A student has at most one subscription that has not expired; the expired ones stay as history.
CREATE UNIQUE INDEX ux_subscriptions_one_current_per_student ON subscriptions (student_id)
    WHERE status <> 'Expired';
-- The periodic check of the subscriptions whose paid period ended.
CREATE INDEX ix_subscriptions_status_current_period_end ON subscriptions (status, current_period_end);

-- The webhook notifications already applied. RevenueCat retries a notification with the same event id until it
-- gets a 200, so the unique event id makes the processing idempotent.
CREATE TABLE processed_webhook_events (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    event_id character varying(255) NOT NULL,
    event_type character varying(50) NOT NULL,
    app_user_id character varying(255),
    environment character varying(20),
    processed_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_processed_webhook_events PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ux_processed_webhook_events_event_id ON processed_webhook_events (event_id);
